# Generated by Django 5.2.2 on 2025-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemShopList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("already_bought", models.BooleanField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mylists.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoplist_name", models.CharField(max_length=20)),
                (
                    "items",
                    models.ManyToManyField(
                        through="mylists.ItemShopList",
                        through_fields=("shop_list", "item"),
                        to="mylists.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemshoplist",
            name="shop_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mylists.shoplist"
            ),
        ),
    ]
